import AIRouter from '../AIRouter.js';
import { truncate } from './agentUtils.js';

export async function WritingAgent({ query, plan, research, finance, factCheck, citation }) {
  const keyStats = (research.keyStats || [])
    .slice(0, 4).map(s => `- ${s.label}: ${s.value} ${s.unit || ''}`.trim()).join('\n');
  const verdict = finance.recommendation || 'Standard institutional review recommended.';
  const reliability = factCheck.overallReliability || 75;

  const prompt = `You are the Senior Report Writer for Economical Research AI, an institutional-grade financial intelligence platform.

Query: "${query}"
Research intent: "${plan.intent}"
Time horizon: ${plan.timeHorizon || 'Last 5 years + 12-month outlook'}

Key Statistics:
${keyStats}

Financial Assessment: Risk Level ${finance.riskLevel || 'MEDIUM'}
Short-term outlook: ${truncate(finance.shortTermOutlook || '', 300)}
Long-term outlook: ${truncate(finance.longTermOutlook || '', 300)}
Overall data reliability: ${reliability}%

Write a comprehensive, authoritative research report with these EXACT sections.
Write as "Economical Research AI" — never mention the AI provider.
Use formal financial journalism style. Be specific with numbers and dates.

# Executive Summary
[3-4 sentences. Lead with the most critical finding. Include one key statistic.]

# Key Findings
- [Finding 1 with specific data point]
- [Finding 2 with specific data point]  
- [Finding 3 with specific data point]
- [Finding 4 with specific data point]
- [Finding 5 with specific data point]

# Background & Context
${truncate(research.background || '', 1200)}

# Current Situation Analysis
${truncate(research.currentSituation || '', 1000)}

# Financial Market Implications
${truncate(finance.marketImpact || '', 800)}

## Sector Impact Assessment
${(finance.sectorImpacts || []).map(s => `**${s.sector}**: ${s.impact} — ${s.detail}`).join('\n')}

# Risk Assessment
**Risk Level: ${finance.riskLevel || 'MEDIUM'}**
${finance.riskJustification || ''}

Key risks to monitor:
${(finance.keyWatchPoints || []).map(w => `- ${w}`).join('\n')}

# Short-Term Outlook (3 months)
${finance.shortTermOutlook || 'Under analysis.'}

# Long-Term Outlook (12-24 months)
${finance.longTermOutlook || 'Under analysis.'}

# ER Verdict
${verdict}

*This analysis was generated by Economical Research AI. Data reliability score: ${reliability}%. ${citation.methodologyNote || ''} This report is for informational purposes only and does not constitute financial advice.*`;

  const report = await AIRouter.route(prompt, 'writing', { maxTokens: 3000 });
  return report || '# Report Generation Failed\n\nPlease try again.';
}
