import React, { useState, useEffect, useRef } from 'react';
import jsPDF from 'jspdf';
import { formatAPA } from '../utils/CitationsFormatter.js';
import ReportViewer from './research/ReportViewer';
import ChartRenderer from './research/ChartRenderer';
import ConfidenceDashboard from './research/ConfidenceDashboard';
import ReadingModeSelector from './research/ReadingModeSelector';
import VersionHistoryPanel from './research/VersionHistoryPanel';
import SourceReliabilityPanel from './research/SourceReliabilityPanel';
import CitationsPanel from './research/CitationsPanel';
import FactCheckMeter from './research/FactCheckMeter';
import RefreshButton from './research/RefreshButton';

function ResearchWorkspace({ 
  report, 
  setReport, 
  running, 
  adapting, 
  queryInput, 
  setQueryInput, 
  handleTriggerResearch, 
  handleRefreshReport,
  handleReadingModeChange,
  activeReadingMode,
  user,
  subscription,
  bookmarkedSections,
  handleBookmarkSection
}) {
  const [mobileLeftOpen, setMobileLeftOpen] = useState(false);
  const [mobileRightOpen, setMobileRightOpen] = useState(false);
  const [isMobile, setIsMobile] = useState(window.innerWidth <= 1024);

  useEffect(() => {
    const handleResize = () => {
      setIsMobile(window.innerWidth <= 1024);
    };
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  if (!report) return null;

  // Extract sections
  const reportSections = report.reportJson?.sections || [];

  // Scroll to section helper
  const scrollToSection = (id) => {
    const element = document.getElementById(id);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
    if (isMobile) {
      setMobileLeftOpen(false);
    }
  };

  // Format citations
  const citations = report?.citation?.scoredSources?.map(src => ({
    text: formatAPA(src)
  })) || [];

  // Format stats
  const quickStats = report?.research?.keyStats?.length ? report.research.keyStats.map(s => ({
    label: s.label,
    value: s.value + (s.unit || '')
  })) : [
    { label: 'Research Confidence', value: `${report.finance?.riskLevel === 'CRITICAL' ? 60 : 85}%` },
    { label: 'Fact Reliability', value: `${report.factCheck?.overallReliability || 75}%` },
    { label: 'Attributed Sources', value: `${report.citation?.scoredSources?.length || 0}` }
  ];

  // PDF Export (FEATURE 5)
  const exportToPDF = () => {
    const pdf = new jsPDF('p', 'mm', 'a4');
    
    pdf.setFillColor(6, 13, 23);
    pdf.rect(0, 0, 210, 297, 'F');
    
    pdf.setTextColor(244, 167, 38);
    pdf.setFontSize(20);
    pdf.setFont('helvetica', 'bold');
    pdf.text('ECONOMICAL RESEARCH', 105, 20, { align: 'center' });
    
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(14);
    pdf.text(report?.query || 'Research Report', 20, 35, { maxWidth: 170 });
    
    pdf.setFontSize(10);
    pdf.setTextColor(180, 180, 180);
    pdf.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 45);
    
    pdf.setDrawColor(244, 167, 38);
    pdf.line(20, 50, 190, 50);
    
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(11);
    
    const reportText = report?.report || '';
    const lines = pdf.splitTextToSize(reportText, 170);
    
    let y = 60;
    lines.forEach(line => {
      if (y > 280) {
        pdf.addPage();
        pdf.setFillColor(6, 13, 23);
        pdf.rect(0, 0, 210, 297, 'F');
        y = 20;
      }
      pdf.text(line, 20, y);
      y += 5;
    });
    
    pdf.setTextColor(244, 167, 38);
    pdf.text('economicalresearch.com', 105, 290, { align: 'center' });
    
    pdf.save(`er-research-${Date.now()}.pdf`);
  };

  // Markdown Export (FEATURE 6)
  const exportMarkdown = () => {
    const md = `# ${report?.query || 'Research Report'}
*Generated by Economical Research AI*
*Date: ${new Date().toLocaleDateString()}*

---

${report?.report || ''}

---

## Citations
${citations.map((c, i) => `[${i+1}] ${c.text}`).join('\n')}

---
*economicalresearch.com*`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `er-research-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // AI Suggestions Handler (FEATURE 3)
  const handleSuggestion = (suggestion) => {
    if (suggestion.includes('Export')) {
      exportToPDF();
      return;
    }

    let nextQuery = '';
    const baseTopic = report?.query || '';

    if (suggestion.includes('Deep dive')) {
      nextQuery = `Deep dive into key aspects of ${baseTopic}`;
    } else if (suggestion.includes('Compare')) {
      nextQuery = `Compare ${baseTopic} across other emerging global markets`;
    } else if (suggestion.includes('Analyze')) {
      nextQuery = `Analyze related companies impacted by ${baseTopic}`;
    } else if (suggestion.includes('SWOT')) {
      nextQuery = `SWOT analysis for ${baseTopic}`;
    } else if (suggestion.includes('timeline')) {
      nextQuery = `Event timeline and future forecasts for ${baseTopic}`;
    } else {
      nextQuery = `${suggestion} relating to ${baseTopic}`;
    }

    setQueryInput(nextQuery);
    handleTriggerResearch(nextQuery);
  };

  return (
    <div className="relative">
      {/* Mobile Top Toolbar Toggles */}
      {isMobile && (
        <div className="flex justify-between items-center bg-[#0A1628] border-b border-[#F4A726]/15 px-4 py-2 text-xs">
          <button 
            onClick={() => { setMobileLeftOpen(!mobileLeftOpen); setMobileRightOpen(false); }}
            className="px-3 py-1.5 bg-[#060D17] border border-[#F4A726]/30 text-[#F4A726] rounded uppercase font-mono font-bold tracking-wider"
          >
            {mobileLeftOpen ? '✕ Navigation' : '☰ Navigation'}
          </button>
          <span className="text-[10px] font-mono text-gray-400">RESEARCH DESK</span>
          <button 
            onClick={() => { setMobileRightOpen(!mobileRightOpen); setMobileLeftOpen(false); }}
            className="px-3 py-1.5 bg-[#060D17] border border-[#F4A726]/30 text-[#F4A726] rounded uppercase font-mono font-bold tracking-wider"
          >
            {mobileRightOpen ? '✕ Dashboard' : '📈 Dashboard'}
          </button>
        </div>
      )}

      {/* Main 3-Panel Layout Grid */}
      <div 
        className="research-workspace"
        style={{
          display: 'grid',
          gridTemplateColumns: isMobile ? '1fr' : '260px 1fr 280px',
          height: 'calc(100vh - 60px)',
          overflow: 'hidden',
          background: '#060D17'
        }}
      >
        {/* Left Sidebar (Desktop layout or mobile overlay) */}
        {(!isMobile || mobileLeftOpen) && (
          <div 
            className="left-sidebar scrollbar-thin"
            style={isMobile ? {
              position: 'absolute',
              top: '37px',
              left: 0,
              width: '260px',
              height: 'calc(100vh - 97px)',
              background: '#060D17',
              zIndex: 99,
              borderRight: '1px solid rgba(244,167,38,0.15)',
              overflowY: 'auto',
              padding: '20px 16px'
            } : {
              borderRight: '1px solid rgba(244,167,38,0.15)',
              overflowY: 'auto',
              padding: '20px 16px'
            }}
          >
            <h3 style={{
              color: '#F4A726', 
              fontSize: '12px',
              textTransform: 'uppercase', 
              letterSpacing: '1px',
              marginBottom: '16px',
              fontWeight: '700'
            }}>
              Research Navigation
            </h3>
            {reportSections.length === 0 ? (
              <p className="text-[11px] text-gray-500 font-mono">No sections indexed yet.</p>
            ) : (
              reportSections.map(section => (
                <div key={section.id}
                  onClick={() => scrollToSection(section.id)}
                  style={{
                    padding: '8px 12px',
                    color: 'rgba(255,255,255,0.6)',
                    fontSize: '13px',
                    cursor: 'pointer',
                    borderRadius: '4px',
                    marginBottom: '4px',
                    transition: 'all 0.2s'
                  }}
                  className="hover:bg-[#F4A726]/10 hover:text-white"
                >
                  {section.title}
                </div>
              ))
            )}
          </div>
        )}

        {/* Center Panel (The report text and interactive elements) */}
        <div style={{ overflowY: 'auto', padding: isMobile ? '20px 16px' : '32px 40px' }} className="scrollbar-thin">
          <RefreshButton 
            generatedAt={report.generatedAt} 
            onRefresh={handleRefreshReport} 
            loading={running} 
          />

          {/* Action Toolbar (Exports, Bookmarks, and Collaboration Placeholders) */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-[#0A1628] border border-[#F4A726]/15 rounded-lg p-4 my-4 shadow">
            {/* Exports */}
            <div className="flex gap-2">
              <button onClick={exportToPDF} style={{
                padding: '10px 20px',
                background: 'transparent',
                color: '#F4A726',
                border: '1px solid #F4A726',
                borderRadius: '6px',
                cursor: 'pointer',
                fontSize: '13px',
                fontWeight: '600'
              }} className="hover:bg-[#F4A726] hover:text-navy transition-colors">
                📄 Export PDF
              </button>
              <button onClick={exportMarkdown} style={{
                padding: '10px 20px',
                background: 'transparent',
                color: '#F4A726',
                border: '1px solid #F4A726',
                borderRadius: '6px',
                cursor: 'pointer',
                fontSize: '13px',
                fontWeight: '600'
              }} className="hover:bg-[#F4A726] hover:text-navy transition-colors">
                📝 Export Markdown
              </button>
            </div>

            {/* Collaboration Placeholders (FEATURE 7) */}
            <div className="flex flex-col items-end gap-1.5">
              <div style={{ display: 'flex', gap: '8px' }}>
                <button title="Coming Soon" style={{ opacity: 0.4 }} className="text-xs bg-transparent text-gray-400 border border-gray-600 rounded px-2.5 py-1.5 cursor-not-allowed">
                  👥 Share Report
                </button>
                <button title="Coming Soon" style={{ opacity: 0.4 }} className="text-xs bg-transparent text-gray-400 border border-gray-600 rounded px-2.5 py-1.5 cursor-not-allowed">
                  💬 Comments
                </button>
                <button title="Coming Soon" style={{ opacity: 0.4 }} className="text-xs bg-transparent text-gray-400 border border-gray-600 rounded px-2.5 py-1.5 cursor-not-allowed">
                  🔒 Permissions
                </button>
              </div>
              <span style={{ fontSize: '11px', color: 'rgba(255,255,255,0.3)' }}>
                Collaboration features coming soon
              </span>
            </div>
          </div>

          {/* Reading Mode Info banner */}
          {adapting && (
            <div className="p-3 bg-[#F4A726]/10 border border-[#F4A726]/30 text-[#F4A726] text-[10px] font-mono rounded animate-pulse mb-4">
              ⚡ Re-compiling report language style to suit target persona...
            </div>
          )}

          {/* The Report Viewer */}
          <ReportViewer 
            report={report} 
            onBookmarkSection={handleBookmarkSection}
            bookmarkedSections={bookmarkedSections}
          />

          {/* Suggestions after report (FEATURE 3) */}
          <div style={{
            marginTop: '32px',
            padding: '24px',
            background: 'rgba(244,167,38,0.05)',
            borderRadius: '12px',
            border: '1px solid rgba(244,167,38,0.15)'
          }}>
            <h3 style={{ color: '#F4A726', marginBottom: '16px', fontSize: '14px', fontWeight: '700' }}>
              Continue Your Research
            </h3>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '10px' }}>
              {[
                '🔍 Deep dive into key topic',
                '🌍 Compare with another country',
                '🏢 Analyze related companies',
                '📊 Generate SWOT analysis',
                '📅 Build event timeline',
                '📄 Export this report'
              ].map(suggestion => (
                <button key={suggestion}
                  onClick={() => handleSuggestion(suggestion)}
                  style={{
                    padding: '10px 16px',
                    background: 'rgba(244,167,38,0.08)',
                    color: '#fff',
                    border: '1px solid rgba(244,167,38,0.2)',
                    borderRadius: '20px',
                    fontSize: '13px',
                    cursor: 'pointer',
                    transition: 'all 0.2s'
                  }}
                  className="hover:bg-[#F4A726]/20 hover:text-white"
                >
                  {suggestion}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Right Sidebar (Desktop layout or mobile overlay) */}
        {(!isMobile || mobileRightOpen) && (
          <div 
            className="right-sidebar scrollbar-thin space-y-6"
            style={isMobile ? {
              position: 'absolute',
              top: '37px',
              right: 0,
              width: '280px',
              height: 'calc(100vh - 97px)',
              background: '#060D17',
              zIndex: 99,
              borderLeft: '1px solid rgba(244,167,38,0.15)',
              overflowY: 'auto',
              padding: '20px 16px'
            } : {
              borderLeft: '1px solid rgba(244,167,38,0.15)',
              overflowY: 'auto',
              padding: '20px 16px'
            }}
          >
            {/* Quick Stats (FEATURE 1) */}
            <div style={{ marginBottom: '24px' }}>
              <h3 style={{
                color: '#F4A726', 
                fontSize: '12px',
                textTransform: 'uppercase', 
                letterSpacing: '1px',
                marginBottom: '12px',
                fontWeight: '700'
              }}>
                Quick Stats
              </h3>
              {quickStats.map(stat => (
                <div key={stat.label} style={{
                  padding: '10px',
                  background: 'rgba(244,167,38,0.05)',
                  borderRadius: '6px',
                  marginBottom: '8px'
                }}>
                  <p style={{
                    color: '#F4A726', 
                    fontSize: '18px',
                    fontWeight: '700', 
                    margin: 0
                  }}>
                    {stat.value}
                  </p>
                  <p style={{
                    color: 'rgba(255,255,255,0.5)',
                    fontSize: '11px', 
                    margin: 0
                  }}>
                    {stat.label}
                  </p>
                </div>
              ))}
            </div>

            {/* Sources (FEATURE 1) */}
            <div style={{ marginBottom: '24px' }}>
              <h3 style={{
                color: '#F4A726', 
                fontSize: '12px',
                textTransform: 'uppercase', 
                letterSpacing: '1px',
                marginBottom: '12px',
                fontWeight: '700'
              }}>
                Sources
              </h3>
              {citations.length === 0 ? (
                <p className="text-[11px] text-gray-500 font-mono">No cited sources indexable.</p>
              ) : (
                citations.map((cite, i) => (
                  <div key={i} style={{
                    fontSize: '11px',
                    color: 'rgba(255,255,255,0.5)',
                    marginBottom: '8px',
                    paddingBottom: '8px',
                    borderBottom: '1px solid rgba(255,255,255,0.05)'
                  }}>
                    [{i+1}] {cite.text}
                  </div>
                ))
              )}
            </div>

            {/* Additional Premium Panels inside Right Sidebar */}
            <ReadingModeSelector 
              activeMode={activeReadingMode} 
              onChangeMode={handleReadingModeChange}
              disabled={running || adapting}
            />

            <ConfidenceDashboard report={report} />

            {!running && user && (
              <VersionHistoryPanel 
                userId={user.uid}
                reportId={report.id || report.reportId}
                currentVersion={report.reportVersion || 1}
                onRestoreReport={(restored) => setReport(restored)}
                onContinueResearch={(v) => { setQueryInput(v.query); setReport(v); }}
              />
            )}

            {report.charts && report.charts.length > 0 && (
              <ChartRenderer charts={report.charts} />
            )}

            {report.factCheck && (
              <FactCheckMeter factCheck={report.factCheck} />
            )}

            {report.citation?.scoredSources && (
              <div className="space-y-6">
                <SourceReliabilityPanel sources={report.citation.scoredSources} />
                <CitationsPanel sources={report.citation.scoredSources} />
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

const MemoizedResearchWorkspace = React.memo(ResearchWorkspace);
export default MemoizedResearchWorkspace;
